apiVersion: apps/v1
kind: Deployment
metadata: 
    name: deploy-two
    labels:
        name: deploytwo
spec:
    replicas: 3
    selector:
        matchLabels:
            name: jtone
    template:
        metadata:
            labels:
                name: jtone
        spec:
            containers:
                - name: javat-con 
                  image: ghogalekunal/javatappimg:latest

